//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya16
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перечень услуг.
    /// </summary>
    [Caption("Перечень услуг")]
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПереченьУслугE", new string[] {
            "Наименование as \'Наименование\'",
            "Empty as \'Empty\'",
            "Empty.Время as \'Время\'"}, Hidden=new string[] {
            "Empty.Время"})]
    [MasterViewDefineAttribute("ПереченьУслугE", "Empty", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Время")]
    [View("ПереченьУслугL", new string[] {
            "Наименование as \'Наименование\'",
            "Empty.Время as \'Время\'"})]
    public class ПереченьУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.Kursovaya16.ЗатрВремя fEmpty;
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ПереченьУслуг.Наименование CustomAttributes)

        // *** End programmer edit section *** (ПереченьУслуг.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ПереченьУслуг.Наименование Get start)

                // *** End programmer edit section *** (ПереченьУслуг.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ПереченьУслуг.Наименование Get end)

                // *** End programmer edit section *** (ПереченьУслуг.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПереченьУслуг.Наименование Set start)

                // *** End programmer edit section *** (ПереченьУслуг.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ПереченьУслуг.Наименование Set end)

                // *** End programmer edit section *** (ПереченьУслуг.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Перечень услуг.
        /// </summary>
        [PropertyStorage(new string[] {
                "ЗатрВремя"})]
        [NotNull()]
        public virtual IIS.Kursovaya16.ЗатрВремя Empty
        {
            get
            {
                IIS.Kursovaya16.ЗатрВремя result = this.fEmpty;
                return result;
            }
            set
            {
                this.fEmpty = value;
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПереченьУслугE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПереченьУслугE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПереченьУслугE", typeof(IIS.Kursovaya16.ПереченьУслуг));
                }
            }
            
            /// <summary>
            /// "ПереченьУслугL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПереченьУслугL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПереченьУслугL", typeof(IIS.Kursovaya16.ПереченьУслуг));
                }
            }
        }
    }
}
